### ISSUE TITLE
Create User Persona

### ISSUE THREAD

**Issue by LyubimaMalkocheva** [yoannary/figma-project-influencerai#1]

**Comment by LyubimaMalkocheva** [comment]
-  Как сме стигнали до това заключение
-  Създаване на атрактивен дизайн
-  Консултиране с още два AI 
- https://gemini.google.com/

**Comment by yoannary** [comment]
## User Persona: Sarah, the Data-Savvy Marketer
## GEMINI AI

**Bio:**

* Name: Sarah Jones
* Age: 32
* Occupation: Marketing Manager at a mid-sized clothing company
* Education: Bachelor's degree in Marketing, currently pursuing an online certification in Data Analytics
* Tech Savvy: Comfortable using various marketing platforms and social media tools. Eager to learn new technologies.

**Personality:**

* Analytical: Sarah loves digging into data and uncovering insights. 
* Driven: Ambitious and results-oriented. She thrives on challenges and wants to see a measurable impact from her marketing efforts.
* Creative: Enjoys using data to inform creative marketing campaigns.

**Preferred Channels:**

* Webinars and online courses related to marketing and data analytics
* Social media platforms like LinkedIn and Twitter for industry trends and news
* Industry blogs and publications focused on marketing technology

**Goals:**

* Improve marketing campaign performance through data-driven decision making
* Gain deeper customer insights to personalize marketing messages
* Identify and partner with relevant influencers for brand promotion
* Stay ahead of the curve in marketing technology trends

**Frustrations:**

* Difficulty accessing and integrating data from various marketing platforms
* Lack of time and resources for in-depth data analysis
* Reliance on gut feeling instead of data-driven strategies
* Outdated marketing tools that limit campaign effectiveness

**Motivations:**

* Increase brand awareness and engagement
* Drive sales and achieve marketing objectives
* Demonstrate the value of marketing through data-driven results
* Advance her career in marketing through continuous learning

**Brands:**

* Sarah follows marketing thought leaders and data analytics companies 
* She's interested in brands that offer innovative marketing solutions and prioritize data security

**Additional Notes:**

* Sarah is an ideal user for InfluencerAI because it addresses her frustrations with traditional marketing tools. 
* She values platforms that are user-friendly and provide actionable insights to optimize her marketing strategies.

**Comment by yoannary** [comment]
## TEAM GPT AI
## User Persona for InfluencerAI

### Bio
**Name:** Emily Carter  
**Age:** 34  
**Location:** San Francisco, CA  
**Occupation:** Digital Marketing Strategist  
**Education:** Master's in Marketing and Data Analytics  

### Personality
Emily is highly analytical, detail-oriented, and innovative. She has a strong capacity for critical thinking and problem-solving. A natural leader, she thrives in collaborative environments but is also self-motivated and capable of working independently. Her approach to challenges is methodical and based on data-driven insights.

### Preferred Channels
1. **LinkedIn** - For professional networking, industry insights, and keeping up with trends.
2. **Twitter** - Quick updates on industry news and a platform for engaging with thought leaders.
3. **Medium** - For in-depth articles on marketing strategies and data analysis.
4. **YouTube** - Educational content and tutorials related to digital marketing and data tools.

### Goals
- **Streamline Data Access:** To simplify the process of accessing big marketing datasets seamlessly.
- **Enhance Decision-Making:** Utilize sophisticated AI tools to generate actionable insights for strategic planning.
- **Boost Campaign Effectiveness:** To create highly targeted marketing campaigns that yield better engagement and conversion rates.
- **Stay Ahead of Trends:** To be always on the cutting edge, using the latest technologies to maintain competitiveness.

### Frustrations
- **Fragmented Tools:** Current tools are disjointed and don't communicate well, making it hard to get a cohesive understanding of data.
- **Outdated Systems:** Struggling with legacy systems that are not built to handle the scale or complexity of modern marketing data.
- **Inefficient Processes:** Wasting too much time compiling and cleaning up data instead of analyzing it and gaining insights.
- **Lack of Creative Freedom:** Feeling that current tools limit the ability to innovate or try new, out-of-the-box marketing strategies.

### Motivations
- **Professional Growth:** Emily is driven by a desire to be recognized as a leader in her field, constantly seeking new skills and knowledge.
- **Impact:** She wants to make a significant impact on her company’s success, directly contributing to growth and profitability.
- **Innovation:** Passionate about leveraging technology to transform traditional marketing practices into dynamic, effective strategies.

### Brands
- **Google Analytics:** Relies on its comprehensive features for basic data analysis.
- **Tableau:** Uses for advanced data visualization.
- **HubSpot:** Appreciates its integration capabilities for managing marketing campaigns.
- **Salesforce:** Utilizes for CRM and further data insights.

InfluencerAI represents an exciting opportunity for Emily to address her frustrations and achieve her goals, leveraging state-of-the-art technology to refine and revolutionize her approach to digital marketing.

**Comment by LyubimaMalkocheva** [comment]
![Image](https://github.com/yoannary/figma-project-influencerai/assets/147819536/07d68ebc-9deb-490a-9003-1a2b77378507)

**Comment by LyubimaMalkocheva** [comment]
![Image](https://github.com/yoannary/figma-project-influencerai/assets/147819536/870aa383-c7c0-4872-b337-ffbaa1f676ed)

**Comment by LyubimaMalkocheva** [comment]
![Image](https://github.com/yoannary/figma-project-influencerai/assets/147819536/e51996e4-405e-4d73-8749-2c2402b4262e)

Version after color changes

**Comment by yoannary** [comment]
Add some blue from the color palette too, if it is possible, because this will be the main color of the project and the purple/pink will be a second one.

**Comment by yoannary** [comment]
@LyubimaMalkocheva Review my comment

**Comment by LyubimaMalkocheva** [comment]
![Image](https://github.com/yoannary/figma-project-influencerai/assets/147819536/0896c567-eee8-4284-947b-4db5de7c2143)
